version: '2'
services:
  snmptrapd:
    build:
      context: ./snmptrapd
    ports:
      - 162:162/udp
    volumes:
      - ./snmp-traps/:/var/log/
    restart: always
  splunk:
    image: splunk/splunk:latest
    ports:
      - 8515:8515
      - 8000:8000
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    volumes:
      - ./splunk/inputs/:/opt/splunk/etc/apps/search/local/
      - ./snmptrapd/snmp-traps:/opt/splunk/var/logs/
    depends_on:
      - snmptrapd
